### ISSUE TITLE
Syntax Error: Non-ASCII character - PEP-0263 launching script on Raspbian

### ISSUE THREAD

**Issue by zero0n3** [ARTEZON/telegraph-image-downloader#2]
Hello
i tried to launche .py script on Raspberry PI 2B but i get:

`  File "download.py", line 115
SyntaxError: Non-ASCII character '\xe2' in file download.py on line 115, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Reading the link i added on the top of py file all the coding lines in the examples (one by one). But , for example, with utf-8 i get this error:

`  File "download.py", line 137
    if this_failed == 0: print(f'     Downloading... {percent}%', end='\r', flush=True)
                                                               ^
SyntaxError: invalid syntax`

**Comment by Artezon** [comment]
Hello
Which python version do you have?

**Comment by zero0n3** [comment]
Hello
, you are right :-)
Using python i supposed to use latest but it was 2.7.16. So i discovered that i also have pyhton3 command that works on 3.7.3 version.

But with 3.7.3, launching the script, i got this:

`Traceback (most recent call last):
  File "download.py", line 30, in <module>
    from os import system, remove, rename, startfile, _exit
ImportError: cannot import name 'startfile' from 'os' (/usr/lib/python3.7/os.py)`

**Comment by Artezon** [comment]
I haven't actually tested it on Linux before. Apparently, I need to make some changes in code for the script to properly run on platforms other than Windows. I'm busy today, so the update can be delayed. I'll try to address the issue as soon as possible.

**Comment by zero0n3** [comment]
Ok no problem. Thanks
When you are ready and you need help for testing i'm here.

**Comment by Artezon** [comment]
Hello
The new version is ready. It has been tested on x86 Ubuntu 22.04 with Python 3.10. Please let me know if the script works on your Raspberry PI before I update the repository.

Download: [TGIDownloader_v1.2.3.zip](https://github.com/ARTEZON/telegraph-image-downloader/files/10184836/TGIDownloader_v1.2.3.zip)

**Comment by zero0n3** [comment]
Hello
now it starts and ask me to click Enter (with Links.txt file) or copy an URL. I press Enter because i have a Links.txt file but it stop immediately by creating an error lo file with this inside:

`Traceback (most recent call last):
  File "TGIDownloader_v1.2.3.py", line 388, in <module>
    main()
  File "TGIDownloader_v1.2.3.py", line 245, in main
    print(f'\nArticle {htmlNumber} of {len(htmlList)}: {title}')
  File "/usr/lib/python3.7/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 27-34: character maps to <undefined>`

**Comment by Artezon** [comment]
Hello. Your file seems to be saved in "iso8859-15" encoding. I implemented only UTF-8 support as it is the most widely used encoding that supports all languages and is a default choice of many text editors. Making support for all encodings would be tricky and unnecessary. I added an error message to not confuse users:
![Screenshot_1](https://user-images.githubusercontent.com/61311568/206576053-99aff417-765e-4479-bb93-93c1073f6dd3.png)

Please, save your file in UTF-8 and try again. Let me know the results. Thanks.

Added error message for unsupported encoding: [TGIDownloader_v1.2.3.zip](https://github.com/ARTEZON/telegraph-image-downloader/files/10189745/TGIDownloader_v1.2.3.zip)

**Comment by zero0n3** [comment]
Hello , this is the encoding of links.txt
`Links.txt: text/plain; charset=utf-8`

now i launch command and i get this error:
```
Traceback (most recent call last):
  File "TGIDownloader_v1.2.3.py", line 126, in getHTML
    html = list(str(bs(requests.get(url).text, features='html.parser')).split('\n'))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '﻿https://telegra.ph/Hencomics-podborka-87-10-31'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TGIDownloader_v1.2.3.py", line 407, in <module>
    main()
  File "TGIDownloader_v1.2.3.py", line 232, in main
    htmlList = getHTML()
  File "TGIDownloader_v1.2.3.py", line 129, in getHTML
    print('[Error] Couldn\'t open this URL:', url)
  File "/usr/lib/python3.7/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>
```

**Comment by ARTEZON** [comment]
Hello
I can't reproduce this error on Python 3.7 and 3.10 even with the same link.

I have no idea why `requests.exceptions.InvalidSchema` exception occurred in your case. Perhaps, it's just a one-time error. The second one, `UnicodeEncodeError`, is thrown when calling `print()` function. There must be something with your terminal encoding, since it says that `[` character can't be encoded. You can try to remove all non-English characters from `print()` functions.

I'm closing this issue now. A new update was released and I hope it will work for you.

**Comment by Artezon** [comment]
I just found out that `\ufeff` is a BOM character (byte order mark). You can save your links file as UTF-8 with BOM and without. Download a new version of my script. If it doesn't work, save your file without BOM.

**Comment by zero0n3** [comment]
Hello.
since with BOM and without BOM I still had error and since the problem seemed to be the character encoding I checked on my Raspbian installation and saw that the local charset was ISO-8859-15.
I changed it to UTF-8 and restarted the Raspberry.

Now with the latest version 1.2.3 I no longer have any problems with the same links for which I had errors.

**Comment by zero0n3** [comment]
Just for testing: i tried a very large bulk massive downloadeing by adding about 50 URL into Links.txt and i didn't get any error. So perhaps, it might make sense to indicate in the script indications that the operating system, if Linux, should be set as UTF-8 Locale
